### ISSUE TITLE
About data process

### ISSUE THREAD

**Issue by LWL-cpu** [sefeoglu/RAG4RE#1]
This is an outstanding work! I have a question regarding the TacRED dataset: how are the /Users/sefika/RAG4RE/data/tacred/test-relations.json  in the dataset obtained? I am currently in urgent need of a processed version of the data. Could you please let me know if there's a way to access a pre-processed version of the dataset or any additional guidance on how to process it myself?

**Comment by sefeoglu** [comment]
Hi,
Thanks. You can request the data from [here](https://catalog.ldc.upenn.edu/LDC2018T24) and I could not share the data due to the license issue. You can repeat the experiments with this update [branch](https://github.com/sefeoglu/RAG4RE/tree/updates) if you have the problem in results. Regarding format, follow this paper: https://arxiv.org/abs/2404.13397
