### ISSUE TITLE
about main.py

### ISSUE THREAD

**Issue by pengcheng-yan** [sefeoglu/RAG4RE#8]
Hello Dear Author, when i run main.py.I have some problem.Please    How was this file generated?
1.  relations_path=/Users/sefika/RAG4RE/data/tacred/rel2id.json
2.  test_ground_truth_path=/Users/sefika/RAG4RE/data/tacred/test-relations.json

**Comment by sefeoglu** [comment]
Hi, 
1.) The rel2id.json is available inside of the dataset: https://catalog.ldc.upenn.edu/LDC2018T24
2.) test-relations.json: it is the list of the 'relation' in the test.json. Unfortunately data is licensed, so I could not share it. If you are a student or academic, you can access it free. Otherwise, it is paid.

I changed the config for semeval, since after refactoring I did some bugs there. You can give the path of test_relation.json to both path.
Best regards.

**Comment by pengcheng-yan** [comment]
sorry,when I have down the DATA  FROM https://catalog.ldc.upenn.edu/LDC2018T24,I only find three formats data,such as json  conll and gold. 
And When I go to github to check other projects, there are also only these three format file soldiers without rel2
id, so I'm asking what you did to get this file?please

**Comment by sefeoglu** [comment]
Hi again, it was a mistake in config.ini about semeval. Thanks for pointing out this. Semeval has this file. For TACRED you do not need it

**Comment by pengcheng-yan** [comment]
1972369322@qq.com     Thanks   very much
